### ISSUE TITLE
Database issues on 1.40

### ISSUE THREAD

**Issue by LogoiLab** [debtcompliance/PdfBook#5]
It appears more functions were deprecated in addition to the incomplete pull request https://github.com/debtcompliance/PdfBook/pull/4
This time it was a database function. I am not a PHP developer. I think it is a vile language. I hope someone else can fix this.

Here is a link to the docs for the file that is erroring:
https://doc.wikimedia.org/mediawiki-core/master/php/classWikimedia_1_1Rdbms_1_1DatabaseMysqli.html#a27b7952327d4edd0a1d75d5c6175a69a

Here is the error:

```
[ba77c4dba6eb4ec91332ede0] /index.php?title=Category:Mac&action=pdfbook Error: Call to undefined method Wikimedia\Rdbms\DatabaseMysqli::fetchRow()

Backtrace:

from /srv/http/includes/libs/rdbms/database/DBConnRef.php(119)
#0 /srv/http/extensions/PdfBook/PdfBookAction.php(81): Wikimedia\Rdbms\DBConnRef->__call()
#1 /srv/http/includes/MediaWiki.php(556): PdfBookAction->show()
#2 /srv/http/includes/MediaWiki.php(333): MediaWiki->performAction()
#3 /srv/http/includes/MediaWiki.php(923): MediaWiki->performRequest()
#4 /srv/http/includes/MediaWiki.php(576): MediaWiki->main()
#5 /srv/http/index.php(50): MediaWiki->run()
#6 /srv/http/index.php(46): wfIndexMain()
#7 {main}
```

You can patch your current implementation to match mine using this patch file

```patch
--- PdfBook.old/PdfBookAction.php	2023-08-07 23:10:13.365930514 +0000
+++ PdfBook/PdfBookAction.php	2023-08-07 23:08:54.564788526 +0000
@@ -18,7 +18,7 @@
 		$user   = $this->getUser();
 		$output = $this->getOutput();
 		$title  = $this->getTitle();
-		$page   = WikiPage::factory( $title );
+		$page   = MediaWikiServices::getInstance()->getWikiPageFactory()->newFromTitle( $title );
 		$book   = $title->getText();
 		$opt    = ParserOptions::newFromUser( $user );

@@ -119,7 +119,7 @@
 			$wgScript = $wgServer . $wgScript;
 			foreach ( $articles as $title ) {
 				if ( is_object( $title ) && $title->exists() ) {
-					$page = WikiPage::factory( $title );
+					$page = MediaWikiServices::getInstance()->getWikiPageFactory()->newFromTitle( $title );
 					$ttext = $title->getPrefixedText();
 					$turl = $title->getFullUrl();
 					if ( !in_array( $ttext, $exclude ) ) {
```

**Comment by LogoiLab** [comment]
It appears I was not utilizing the right code from the fork in the pull request.

You should consider merging #4

**Comment by absort0** [comment]
#4 merged, thanks for reporting @LogoiLab 
I'm closing this now.
