### ISSUE TITLE
Use of SkinTemplateNavigation hook was deprecated

### ISSUE THREAD

**Issue by drhirn** [debtcompliance/PdfBook#6]
Using MW 1.39.5 with the lts Docker image, I get the following error when including PdfBook-Extension:

````
Deprecated: Use of SkinTemplateNavigation hook (used in PdfBookHooks::onSkinTemplateNavigation) was deprecated in MediaWiki 1.39. [Called from MediaWiki\HookContainer\HookContainer::run in /var/www/html/includes/HookContainer/HookContainer.php at line 137] in /var/www/html/includes/debug/MWDebug.php on line 38
````

Tried branches master and REL1_39. Same with both. As soon, as I uncomment the wfLoadExtension for PdfBook in LocalSettings.php, everything is working fine again.

Anything I can do to help?

**Comment by absort0** [comment]
Hi @drhirn, thanks for submitting this issue.

We are using MW 1.39.5 with PdfBook with no issues. I personally haven't tested with Docker, but the deprecated warning is expected and not fatal, so this shouldn't be the cause of your wiki not working.

We of course plan on moving away from this deprecated hook in the near future to ensure compatibility with next MW versions, but this is not a priority at the moment.

If you want to share more information about your issue, specifically if you could share a full backtrace I might be able to help you further.

Thanks again for using PdfBook and for opening the issue.

**Comment by kghbln** [comment]
@drhirn Add [`$wgDeprecationReleaseLimit = '1.35';`](https://www.mediawiki.org/wiki/Manual:$wgDeprecationReleaseLimit) to your LocalSettings.php to silence these deprecation notices.

**Comment by drhirn** [comment]
Ok, will try. Thx!

And hope to get back to @absort0 next week with a full backtrace and some more information.

**Comment by drhirn** [comment]
Finally managed to get a full backtrace for you

````
Deprecated: Use of SkinTemplateNavigation hook (used in PdfBookHooks::onSkinTemplateNavigation) was deprecated in MediaWiki 1.39. [Called from MediaWiki\HookContainer\HookContainer::run in /var/www/html/includes/HookContainer/HookContainer.php at line 137] in /var/www/html/includes/debug/MWDebug.php on line 381
MediaWiki internal error.

Original exception: [3c9eb7fd9f2fac2fd914379a] /wiki/Hauptseite Error: Call to undefined method User::isLoggedIn()
Backtrace:
from /var/www/html/extensions/PdfBook/PdfBookHooks.php(21)
#0 /var/www/html/includes/HookContainer/HookContainer.php(338): PdfBookHooks::onSkinTemplateNavigation(MediaWiki\Skins\Vector\SkinVectorLegacy, array)
#1 /var/www/html/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#2 /var/www/html/includes/HookContainer/HookRunner.php(3524): MediaWiki\HookContainer\HookContainer->run(string, array, array)
#3 /var/www/html/includes/skins/SkinTemplate.php(1195): MediaWiki\HookContainer\HookRunner->onSkinTemplateNavigation(MediaWiki\Skins\Vector\SkinVectorLegacy, array)
#4 /var/www/html/skins/Vector/includes/SkinVector.php(350): SkinTemplate->runOnSkinTemplateNavigationHooks(MediaWiki\Skins\Vector\SkinVectorLegacy, array)
#5 /var/www/html/includes/skins/SkinTemplate.php(1574): MediaWiki\Skins\Vector\SkinVector->runOnSkinTemplateNavigationHooks(MediaWiki\Skins\Vector\SkinVectorLegacy, array)
#6 /var/www/html/includes/skins/SkinTemplate.php(790): SkinTemplate->buildContentNavigationUrlsInternal()
#7 /var/www/html/includes/skins/SkinTemplate.php(229): SkinTemplate->getPortletsTemplateData()
#8 /var/www/html/includes/skins/SkinMustache.php(88): SkinTemplate->getTemplateData()
#9 /var/www/html/skins/Vector/includes/SkinVector.php(454): SkinMustache->getTemplateData()
#10 /var/www/html/includes/skins/SkinMustache.php(58): MediaWiki\Skins\Vector\SkinVector->getTemplateData()
#11 /var/www/html/includes/skins/SkinTemplate.php(177): SkinMustache->generateHTML()
#12 /var/www/html/includes/OutputPage.php(2876): SkinTemplate->outputPage()
#13 /var/www/html/includes/MediaWiki.php(922): OutputPage->output(boolean)
#14 /var/www/html/includes/MediaWiki.php(562): MediaWiki->main()
#15 /var/www/html/index.php(50): MediaWiki->run()
#16 /var/www/html/index.php(46): wfIndexMain()
#17 {main}

Exception caught inside exception handler: [3c9eb7fd9f2fac2fd914379a] /wiki/Hauptseite Error: Call to undefined method User::isLoggedIn()
Backtrace:
from /var/www/html/extensions/PdfBook/PdfBookHooks.php(21)
#0 /var/www/html/includes/HookContainer/HookContainer.php(338): PdfBookHooks::onSkinTemplateNavigation(MediaWiki\Skins\Vector\SkinVectorLegacy, array)
#1 /var/www/html/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#2 /var/www/html/includes/HookContainer/HookRunner.php(3524): MediaWiki\HookContainer\HookContainer->run(string, array, array)
#3 /var/www/html/includes/skins/SkinTemplate.php(1195): MediaWiki\HookContainer\HookRunner->onSkinTemplateNavigation(MediaWiki\Skins\Vector\SkinVectorLegacy, array)
#4 /var/www/html/skins/Vector/includes/SkinVector.php(350): SkinTemplate->runOnSkinTemplateNavigationHooks(MediaWiki\Skins\Vector\SkinVectorLegacy, array)
#5 /var/www/html/includes/skins/SkinTemplate.php(1574): MediaWiki\Skins\Vector\SkinVector->runOnSkinTemplateNavigationHooks(MediaWiki\Skins\Vector\SkinVectorLegacy, array)
#6 /var/www/html/includes/skins/SkinTemplate.php(790): SkinTemplate->buildContentNavigationUrlsInternal()
#7 /var/www/html/includes/skins/SkinTemplate.php(229): SkinTemplate->getPortletsTemplateData()
#8 /var/www/html/includes/skins/SkinMustache.php(88): SkinTemplate->getTemplateData()
#9 /var/www/html/skins/Vector/includes/SkinVector.php(454): SkinMustache->getTemplateData()
#10 /var/www/html/includes/skins/SkinMustache.php(58): MediaWiki\Skins\Vector\SkinVector->getTemplateData()
#11 /var/www/html/includes/skins/SkinTemplate.php(177): SkinMustache->generateHTML()
#12 /var/www/html/includes/OutputPage.php(2876): SkinTemplate->outputPage()
#13 /var/www/html/includes/exception/MWExceptionRenderer.php(183): OutputPage->output()
#14 /var/www/html/includes/exception/MWExceptionRenderer.php(102): MWExceptionRenderer::reportHTML(Error)
#15 /var/www/html/includes/exception/MWExceptionHandler.php(131): MWExceptionRenderer::output(Error, integer
````

Using the following:

- MediaWiki 1.39.5
- PHP | 8.1.26 (apache2handler)
- MariaDB | 11.2.2-MariaDB-1:11.2.2+maria~ubu2204
- ICU | 72.1
- Lua | 5.1.5
- Pygments | 2.11.2
- PdfBook 2.0.5, 2021-07-19 (90a4944)

Docker image is `mediawiki:lts`. I'm building my own image with it to integrate extensions. Getting PdfBook with `git clone -b REL1_39 --depth 1 https://gitlab.com/organicdesign/PdfBook.git`. No change if I use PdfBooks `master`.

Dockerfile:
```
# syntax=docker/dockerfile:1

FROM mediawiki:lts

COPY ./composer.local.json /var/www/html

RUN apt update && apt upgrade -y && apt install --no-install-recommends --quiet --yes \
  htmldoc \
  libzip4 \
  unzip \
  wget && \

git clone -b REL1_39 --depth 1 https://gitlab.com/organicdesign/PdfBook.git /var/www/html/extensions/PdfBook && \
git clone --depth 1 https://gerrit.wikimedia.org/r/mediawiki/extensions/AdminLinks.git /var/www/html/extensions/AdminLinks && \
git clone --depth 1 https://phabricator.wikimedia.org/diffusion/EHET/extension-headertabs.git /var/www/html/extensions/HeaderTabs && \
git clone -b REL1_39 --depth 1 https://gerrit.wikimedia.org/r/mediawiki/extensions/LabeledSectionTransclusion.git /var/www/html/extensions/LabeledSectionTransclusion && \
git clone --depth 1 https://github.com/wikimedia/mediawiki-extensions-Arrays.git /var/www/html/extensions/Arrays && \
git clone --depth 1 https://gerrit.wikimedia.org/r/mediawiki/extensions/UrlGetParameters.git /var/www/html/extensions/UrlGetParameters && \
git clone -b REL1_39 --depth 1 https://gerrit.wikimedia.org/r/mediawiki/extensions/UploadWizard /var/www/html/extensions/UploadWizard && \
git clone --depth 1 https://gerrit.wikimedia.org/r/mediawiki/extensions/PageSchemas.git /var/www/html/extensions/PageSchemas && \

wget https://getcomposer.org/download/latest-stable/composer.phar && \

php composer.phar update --no-dev --no-progress && \

chown www-data:www-data -R /var/www/html/images && chown www-data:www-data -R /var/www/html/cache
```

composer.local.json:
```
{
    "require": {
		"mediawiki/semantic-media-wiki": "^4.0",
		"mediawiki/page-forms": "^5.3.4",
		"mediawiki/semantic-forms-select": "dev-master",
		"mediawiki/semantic-result-formats": "~4.0"
    }
}
```

Excerpt from LocalSettings.php:
```
$wgDefaultSkin = "vector";

wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );

wfLoadExtension( 'PdfBook' );

$wgPdfBookTab = true;
```

**Comment by absort0** [comment]
Thanks for the backtrace, @drhirn.
The exception is being caused by the call to the `User::isLoggedIn()` method which was removed in version 1.36.
This method is not called by the extension in the `master` branch. So the backtrace can only be from when you were using the `1.39` branch. 

Please confirm that you are using the `master` branch and check the backtrace again. 

Thanks for reporting!

**Comment by drhirn** [comment]
Well. Somehow I didn't realize, you moved from GitLab to GitHub. Although I posted the issue here. 🤦
My Dockerbuild file was quite old.

When cloning from GitHub, i get the real `master` and everything is working fine. Thanks for pushing me in the right direction.
