### ISSUE TITLE
Errors in 1.39.7

### ISSUE THREAD

**Issue by MichelleMegurine** [debtcompliance/PdfBook#7]
Hi! I'm eager to use this extension in my locally hosted wiki, but nothing seems to work.
I've added the [{{fullurl:{{FULLPAGENAME}}|action=pdfbook}} download this selection of pages as a PDF book] line in the Mediawiki:Category-article-count page, but it gets an error everytime I clic it on a Category page.
I've set to true the $wgPdfBookTab parameter, but it only downloads an empty (0 kb, error when opening) pdf.
Just in case is important, besides being locally hosted, I have the "DisplayTitle" and "NoTitle" extensions installed.

**Comment by absort0** [comment]
Hi @MichelleMegurine thank you for opening this issue. 

I'm sorry you are unable to use the extension.

Would you mind sharing the error message you are getting? 
Can you also try calling the extension directly in the URL to make sure it is not something related to the parser function? Like so: https://YOURWIKIADDRESS/wiki/index.php?title=Category:foo&action=pdfbook <- make sure to adapt the address to your context

**Comment by MichelleMegurine** [comment]
The error message varies, but here are some I got (my wiki is in Spanish):
- [942c8a42a0d55d1b5592ed10] 2024-04-17 00:30:33: Excepción grave de tipo "Error"
- [ac20d6df38657bea350d4983] 2024-04-17 00:31:03: Excepción grave de tipo "Error"
- [7b0563963b3c66366f59bf7d] 2024-04-17 00:31:31: Excepción grave de tipo "Error"
They show in a page of "Internal Error".

I also tried calling the extension in the URL, but got similar internal errors.

**Comment by MichelleMegurine** [comment]
Okay! Got different error codes, but the text is the same:

```
[68d4dab1a2d3f42abc9e9159] /fangirlbook/index.php?title=Categor%C3%ADa:OC.0001&action=pdfbook Error: Call to undefined method Wikimedia\Rdbms\DatabaseSqlite::fetchRow()

Backtrace:

from C:\xampp\htdocs\fangirlbook\includes\libs\rdbms\database\DBConnRef.php(103)
#0 C:\xampp\htdocs\fangirlbook\extensions\PdfBook\PdfBookAction.php(81): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#1 C:\xampp\htdocs\fangirlbook\includes\MediaWiki.php(542): PdfBookAction->show()
#2 C:\xampp\htdocs\fangirlbook\includes\MediaWiki.php(322): MediaWiki->performAction(MediaWiki\Extension\CategoryTree\CategoryTreeCategoryPage, Title)
#3 C:\xampp\htdocs\fangirlbook\includes\MediaWiki.php(904): MediaWiki->performRequest()
#4 C:\xampp\htdocs\fangirlbook\includes\MediaWiki.php(562): MediaWiki->main()
#5 C:\xampp\htdocs\fangirlbook\index.php(50): MediaWiki->run()
#6 C:\xampp\htdocs\fangirlbook\index.php(46): wfIndexMain()
#7 {main}
```

**Comment by absort0** [comment]
Hi @michellemegurine, sorry for the silence I've been very busy lately and although I tried debugging this here and there I didn't had any breakthrough so far. What I have noticed - and would like to ask you to try on your end as well if possible - is that if you call the API with the *single* option and just after call it with *category* it works for some reason. 

Can you check if that works for you as well? It might be a temporary workaround for you to be able to print your PDF and it will also give me more information to debug this. Thanks a lot!

1. /fangirlbook/index.php?title=Categor%C3%ADa:OC.0001&action=pdfbook&format=single
2. /fangirlbook/index.php?title=Categor%C3%ADa:OC.0001&action=pdfbook&format=category

**Comment by MichelleMegurine** [comment]
No results:
1. Shows me a "Empty/Error" PDF.
2. Gives me the following Internal Error:
`[5466a210447a27b8ed0afc74] /fangirlbook/index.php?title=Categor%C3%ADa:OC.0001&action=pdfbook&format=category Error: Call to undefined method Wikimedia\Rdbms\DatabaseSqlite::fetchRow()

Backtrace:

from C:\xampp\htdocs\fangirlbook\includes\libs\rdbms\database\DBConnRef.php(103)
#0 C:\xampp\htdocs\fangirlbook\extensions\PdfBook\PdfBookAction.php(81): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#1 C:\xampp\htdocs\fangirlbook\includes\MediaWiki.php(542): PdfBookAction->show()
#2 C:\xampp\htdocs\fangirlbook\includes\MediaWiki.php(322): MediaWiki->performAction(MediaWiki\Extension\CategoryTree\CategoryTreeCategoryPage, Title)
#3 C:\xampp\htdocs\fangirlbook\includes\MediaWiki.php(904): MediaWiki->performRequest()
#4 C:\xampp\htdocs\fangirlbook\includes\MediaWiki.php(562): MediaWiki->main()
#5 C:\xampp\htdocs\fangirlbook\index.php(50): MediaWiki->run()
#6 C:\xampp\htdocs\fangirlbook\index.php(46): wfIndexMain()
#7 {main}`

**Comment by absort0** [comment]
Hello again @MichelleMegurine 

I'm unable to replicate this on my side, I'm wondering if this has something to do with SqLite or the fact that you are running XAMPP. Even in my local setup which is in some way similar to yours - although using LAMP - I can generate books normally. 

Although the error implies that the method `fetchRow`  doesn't exist, that is not the case, so I think it is being triggered by your database being inaccessible. 

Would it be possible for you to try using a different DB, mysql for example? I know changing database requires a lot of effort, but I don't know what else to suggest.

Also, are you able to generate `single` PdfBooks? 
`/fangirlbook/index.php?title=ANY_NORMAL_PAGE_THAT_IS_NOT_A_CATEGORY&action=pdfbook&format=single`

Thanks!

**Comment by absort0** [comment]
Hi @MichelleMegurine, 

After a proposal sent to me by Peter Nomigkeit via email, I have implemented a patch that might help us understand your issue. Now PdfBook will display an error if HTMLDoc is not found on your system, which is very likely the underlying issue on your case. 

Please test creating a PDF with the latest version and let me know how it goes.

https://github.com/debtcompliance/PdfBook/commit/19a0fccba6ca427b6cc6aeb5332206247c8ffa2c

**Comment by absort0** [comment]
closing stale issue.
